### ISSUE TITLE
Crashing of the applicaton when loging out and logging in

### ISSUE THREAD

**Issue by gregdiaz125** [Benjamin-Pasternak/Security_project#4]
I made a user lil: with password lil. then i logged into the server being localy hoasted, Leon and port 8081.  after i logged in i then log out. i then log back in and the client crashes. 

The client output
```shell
Traceback (most recent call last):
  File "/home/greg/Documents/Operating_systems/bug_hunt/Security_project/client-gui.py", line 286, in show_message
    encoded = ast.literal_eval(encoded)
  File "/usr/lib/python3.9/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 0
 
SyntaxError: unexpected EOF while parsing
zsh: abort (core dumped)  python3 client-gui.py
```
The server output
 ```shell
Host: Leon @ 127.0.1.1
New user IP and Port: ('127.0.0.1', 46674)
New user's username is LIL
Message:  New user LIL joined the chat
['LIL']
Message:  USERLIST['LIL']
[<socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.1.1', 8081), raddr=('127.0.0.1', 46674)>]
<socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.1.1', 8081), raddr=('127.0.0.1', 46674)>
New user IP and Port: ('127.0.0.1', 46676)
New user's username is LIL
Message:  New user LIL joined the chat
['LIL', 'LIL']
Message:  USERLIST['LIL', 'LIL']
Message:  LIL left the chat
[<socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.1.1', 8081), raddr=('127.0.0.1', 46676)>]
how
<socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.1.1', 8081), raddr=('127.0.0.1', 46676)>
[<socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.1.1', 8081), raddr=('127.0.0.1', 46676)>]
<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/greg/Documents/Operating_systems/bug_hunt/Security_project/cs419server2.py", line 121, in client_handler
    clientIndex = clientList.index(client)
ValueError: <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0> is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/greg/Documents/Operating_systems/bug_hunt/Security_project/cs419server2.py", line 130, in client_handler
    clientIndex = clientList.index(client)
ValueError: <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0> is not in list
Message:  LIL left the chat
how
[]
<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/greg/Documents/Operating_systems/bug_hunt/Security_project/cs419server2.py", line 121, in client_handler
    clientIndex = clientList.index(client)
ValueError: <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0> is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/greg/Documents/Operating_systems/bug_hunt/Security_project/cs419server2.py", line 130, in client_handler
    clientIndex = clientList.index(client)
ValueError: <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0> is not in list


 ```

**Comment by symxmyz233** [comment]
This can be **a minor bug.**
